apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: example
      image: example
      ports:
        - containerPort: 80
      env:
        - name: APP
          value: test