apiVersion: v1
kind: Pod
metadata:
  name: name
spec:
  containers:
    - name: test
      image: test
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config
      env:
        - name: VALUE
          valueFrom:
            configMapKeyRef:
              key: VALUE
              name: app-config
